##################################
#                                #
#   EDA Video Game Analysis      #
#        by: Murilao             #
#                                #
##################################


# the dataset contains a list of video game sells greater than 100,000
# copies. It was generated by vgchartz.com

# libraries 
library(hrbrthemes) # not sure what this package does but probably graph themes
library(gganimate)
library(gapminder)
library(babynames) # same with this and cowplot, not sure what they are used for
library(ggthemes)
library(cowplot)
library(ggplot2)

# Data Manipulation
library(dplyr)

# Statistics
library(DescTools)

# Loading the database 
data <- read.csv("vgsales.csv", stringsAsFactors = FALSE)

# Removing the Rank column
data$Rank <- NULL
# It looks like the rank column was just a result from improper copying
# to excel. It is not relevant to the data and could cause problems in the
# analysis process


# Filtering only the records of interest for this study, 
# removing the records with Year = NaN and records with the year above 
# 2016

# they used the following code
data <- data[data$Year != "N/A" & data$Year != "2017" & 
               data$Year != "2020", ]
# but I probably would have filtered with 
data <- data %>% filter(Year != "N/A" & Year != "2017" & Year != "2020")

data$Year <- factor(data$Year)
# Year is currently character, but because it is categorical we will change
# it to a factor.

# Viewing the first 6 DataFrame records
head(data, 6)

# they then proceeded to get a summary of the data
summary(data)

# the author then makes a frequency table for the counts of videogames that 
# sold over 100,000 copies in each year. They then add the percentage of
# total games represented by each year
freq_year <- data.frame(cbind(Frequency = table(data$Year), 
                              Percent = prop.table(table(data$Year)) * 100))
freq_year <- freq_year[order(freq_year$Frequency, decreasing=TRUE), ]
freq_year

